apiVersion: v1
kind: Secret
metadata:
  name: eureka-pro-secret
  namespace: eureka-pro
type: Opaque
stringData:
  EUREKA_PRO_EUREKA_CLIENT_PASSWORD: client123
  EUREKA_PRO_GATEWAY_AUTH_TOKEN: gateway-token
