server:
  port: 8081

spring:
  application:
    name: demo-service-a

eureka-pro:
  eureka:
    client-username: eureka-client
    client-password: client123

eureka:
  client:
    service-url:
      defaultZone: http://${eureka-pro.eureka.client-username}:${eureka-pro.eureka.client-password}@localhost:8761/eureka/,http://${eureka-pro.eureka.client-username}:${eureka-pro.eureka.client-password}@localhost:8762/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info
