server:
  port: 8761

spring:
  application:
    name: eureka-server
  thymeleaf:
    cache: false

eureka-pro:
  eureka:
    client-username: eureka-client
    client-password: client123
  security:
    users:
      - username: admin
        password: admin123
        roles:
          - ADMIN
          - VIEWER
      - username: viewer
        password: viewer123
        roles:
          - VIEWER
      - username: eureka-client
        password: client123
        roles:
          - CLIENT

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    response-cache-update-interval-ms: 3000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    com.eurekapro: INFO
    com.netflix.eureka: INFO
